
import Footer from './components/Footer'
import Header from './components/Header'
import NewHeader from './components/NewHeader'
import NewHeaderCopy from './components/NewHeaderCopy'

import './globals.css'

import { Nunito } from 'next/font/google'
// import { Roboto } from 'next/font/google'
// import { Mulish } from 'next/font/google'

const font = Nunito({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'Pdfage App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        {/* <NewHeader /> */}
        {/* <NewHeaderCopy/> */}
        {children}
        <Footer />
      </body>
    </html>
  )
}
